version: '3'
services:
  bokeh-app:
    build: ./bokeh_app
    ports:
      - '5006:5006'
    command: bokeh serve --show bokeh_app --allow-websocket-origin="*"
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - bokeh-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
